import { useState } from 'react';
import { CalendarPlus, ChevronLeft, ChevronRight, Clock3, Video } from 'lucide-react';
import { Button, Card, Field, Modal, Page, PageHeader, Pill } from './ui';
import { sessions as seed } from './data';

const PTSessions=()=>{const [sessions,setSessions]=useState(seed);const [open,setOpen]=useState(false);const [member,setMember]=useState('');const add=()=>{if(member)setSessions([...sessions,{id:Date.now(),time:'09:00',period:'AM',member,type:'PT session',duration:'60 min',status:'Upcoming'}]);setOpen(false);setMember('')};return <Page><PageHeader title="PT sessions" description="Plan, conduct and follow up on one-to-one coaching sessions." actions={<Button onClick={()=>setOpen(true)}><CalendarPlus className="h-4 w-4"/>Schedule session</Button>}/>
  <Card><div className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-100 p-4"><div className="flex items-center gap-2"><Button variant="secondary" className="!p-2"><ChevronLeft className="h-4 w-4"/></Button><h3 className="min-w-40 text-center font-semibold">24–30 August 2026</h3><Button variant="secondary" className="!p-2"><ChevronRight className="h-4 w-4"/></Button></div><Button variant="secondary">Today</Button></div><div className="grid min-w-[760px] grid-cols-7 border-b border-gray-100 bg-gray-50 text-center text-xs font-semibold text-gray-500">{['MON 24','TUE 25','WED 26','THU 27','FRI 28','SAT 29','SUN 30'].map((d)=><div key={d} className={`p-3 ${d.includes('27')?'bg-teal-50 text-teal-700':''}`}>{d}</div>)}</div><div className="overflow-x-auto"><div className="grid min-h-56 min-w-[760px] grid-cols-7 divide-x divide-gray-100 p-3">{[0,1,2,3,4,5,6].map((day)=><div key={day} className="space-y-2 px-1">{day===3&&sessions.map((s)=><div key={s.id} className="rounded-xl border-l-4 border-teal-500 bg-teal-50 p-3"><p className="text-xs font-bold text-teal-900">{s.time} {s.period}</p><p className="mt-1 truncate text-sm font-semibold">{s.member}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-gray-500"><Clock3 className="h-3 w-3"/>{s.duration}</p></div>)}{day===5&&<div className="rounded-xl border-l-4 border-violet-400 bg-violet-50 p-3"><p className="text-xs font-bold">10:00 AM</p><p className="mt-1 text-sm font-semibold">Group mobility</p><p className="text-[11px] text-gray-500">6 members</p></div>}</div>)}</div></div></Card>
  <div className="grid gap-4 md:grid-cols-3">{sessions.slice(0,3).map(s=><Card key={s.id} className="p-4"><div className="flex justify-between"><Pill tone={s.status==='Completed'?'green':'blue'}>{s.status}</Pill><Video className="h-4 w-4 text-gray-400"/></div><p className="mt-4 font-semibold">{s.member}</p><p className="mt-1 text-sm text-gray-500">{s.type} · {s.duration}</p></Card>)}</div>
  <Modal open={open} title="Schedule PT session" onClose={()=>setOpen(false)} footer={<><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={add}>Schedule</Button></>}><div className="space-y-4"><Field label="Member name" value={member} onChange={e=>setMember(e.target.value)} placeholder="Select or enter a member"/><div className="grid grid-cols-2 gap-3"><Field label="Date" type="date" defaultValue="2026-08-28"/><Field label="Time" type="time" defaultValue="09:00"/></div><Field label="Session focus" placeholder="e.g. Lower body strength"/></div></Modal>
  </Page>};export default PTSessions;
